"""add profile fields to users

Revision ID: a655c7461011
Revises: eca7137a9409
Create Date: 2025-09-17 01:54:31.240111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a655c7461011'
down_revision: Union[str, Sequence[str], None] = 'eca7137a9409'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('skills', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('users', sa.Column('experience', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('users', sa.Column('avatar_path', sa.String(length=512), nullable=True))
    op.add_column('users', sa.Column('avatar_filename', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('company_name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('company_website', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('company_description', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('logo_path', sa.String(length=512), nullable=True))
    op.add_column('users', sa.Column('logo_filename', sa.String(length=255), nullable=True))
    op.drop_column('users', 'profile_picture')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_picture', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'logo_filename')
    op.drop_column('users', 'logo_path')
    op.drop_column('users', 'company_description')
    op.drop_column('users', 'company_website')
    op.drop_column('users', 'company_name')
    op.drop_column('users', 'avatar_filename')
    op.drop_column('users', 'avatar_path')
    op.drop_column('users', 'experience')
    op.drop_column('users', 'skills')
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###
