"""Created Application Table

Revision ID: d84eb5a37a6a
Revises: 7b9e5360ffa2
Create Date: 2025-09-10 00:42:30.157682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd84eb5a37a6a'
down_revision: Union[str, Sequence[str], None] = '7b9e5360ffa2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('applications', sa.Column('job_id', sa.Integer(), nullable=False))
    op.add_column('applications', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('applications', sa.Column('resume_path', sa.String(length=512), nullable=True))
    op.add_column('applications', sa.Column('resume_filename', sa.String(length=255), nullable=True))
    op.add_column('applications', sa.Column('cover_letter', sa.Text(), nullable=True))
    op.add_column('applications', sa.Column('status', sa.String(length=50), nullable=False))
    op.add_column('applications', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.create_index(op.f('ix_applications_id'), 'applications', ['id'], unique=False)
    op.create_foreign_key(None, 'applications', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'applications', 'jobs', ['job_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'applications', type_='foreignkey')
    op.drop_constraint(None, 'applications', type_='foreignkey')
    op.drop_index(op.f('ix_applications_id'), table_name='applications')
    op.drop_column('applications', 'created_at')
    op.drop_column('applications', 'status')
    op.drop_column('applications', 'cover_letter')
    op.drop_column('applications', 'resume_filename')
    op.drop_column('applications', 'resume_path')
    op.drop_column('applications', 'user_id')
    op.drop_column('applications', 'job_id')
    op.drop_column('applications', 'id')
    # ### end Alembic commands ###
